import { Job } from '../type/dummy';

export const job: Job[] = [
    { id: 1, title: 'VP Sales', name: 'Gigi Gland' },
    { id: 2, title: 'Account Representative II', name: 'Diann Scala' },
    { id: 3, title: 'Internal Auditor', name: 'Kennedy Lazenbury' },
    { id: 4, title: 'Geologist IV', name: 'Bekki Hutcheon' },
    { id: 5, title: 'Graphic Designer', name: 'Cordey Di Maria' },
    { id: 6, title: 'Social Worker', name: 'Jemmie Bratley' },
    { id: 7, title: 'Community Outreach Specialist', name: "Ainslee O'Fallowne" },
    { id: 8, title: 'Senior Cost Accountant', name: 'Helga Lassell' },
    { id: 9, title: 'Automation Specialist IV', name: 'Arturo McCraw' },
    { id: 10, title: 'Environmental Tech', name: 'Margi Von Hindenburg' },
    { id: 11, title: 'Help Desk Operator', name: 'Garrott Winteringham' },
    { id: 12, title: 'Pharmacist', name: 'Marian Whiskin' },
    { id: 13, title: 'Marketing Manager', name: 'Barnard Di Giacomettino' },
    { id: 14, title: 'Technical Writer', name: 'Griffin Cumberbatch' },
    { id: 15, title: 'Recruiting Manager', name: 'Nil Goreway' },
    { id: 16, title: 'Media Manager III', name: 'Porter Heigl' },
    { id: 17, title: 'Environmental Specialist', name: 'Giuseppe Moncrieffe' },
    { id: 18, title: 'Nurse Practicioner', name: 'Elijah Burns' },
    { id: 19, title: 'Help Desk Operator', name: 'Spike Wescott' },
    { id: 20, title: 'VP Quality Control', name: 'Cirstoforo Bolitho' },
    { id: 21, title: 'Electrical Engineer', name: 'Levon Sayers' },
    { id: 22, title: 'Information Systems Manager', name: 'Glyn Balchen' },
    { id: 23, title: 'Chemical Engineer', name: 'Salaidh Sirmond' },
    { id: 24, title: 'Actuary', name: 'Monty Shewring' },
    { id: 25, title: 'Budget/Accounting Analyst I', name: 'Miltie Dwelling' },
    { id: 26, title: 'Associate Professor', name: 'Bari Ciccottini' },
    { id: 27, title: 'GIS Technical Architect', name: 'Thaddeus Boome' },
    { id: 28, title: 'Structural Analysis Engineer', name: 'Cornelius Lovat' },
    { id: 29, title: 'Business Systems Development Analyst', name: 'Deb Standbrooke' },
    { id: 30, title: 'Mechanical Systems Engineer', name: 'Isiahi Worsnip' },
    { id: 31, title: 'Software Engineer IV', name: 'Kristyn Ferras' },
    { id: 32, title: 'Office Assistant II', name: 'Jourdan Hanssmann' },
    { id: 33, title: 'VP Product Management', name: 'Rhody MacSorley' },
    { id: 34, title: 'VP Product Management', name: 'Clara Road' },
    { id: 35, title: 'Automation Specialist IV', name: 'Pearce Sked' },
    { id: 36, title: 'Environmental Tech', name: 'Nelia Petegrew' },
    { id: 37, title: 'Biostatistician I', name: 'Roxanna Millhill' },
    { id: 38, title: 'Product Engineer', name: 'Alvinia Guwer' },
    { id: 39, title: 'Director of Sales', name: 'Nady Longcake' },
    { id: 40, title: 'Tax Accountant', name: 'Miles McAndie' },
    { id: 41, title: 'Assistant Professor', name: 'Sheilah Norgate' },
    { id: 42, title: 'Structural Engineer', name: 'Stefano Elvidge' },
    { id: 43, title: 'Analog Circuit Design manager', name: 'Ermengarde Scarlon' },
    { id: 44, title: 'Product Engineer', name: 'Hans Ninnis' },
    { id: 45, title: 'Geologist III', name: 'Fair Scanterbury' },
    { id: 46, title: 'Staff Accountant IV', name: 'Yoko Beard' },
    { id: 47, title: 'Social Worker', name: 'Elwyn Correa' },
    { id: 48, title: 'Internal Auditor', name: 'Creighton Cleare' },
    { id: 49, title: 'Internal Auditor', name: 'Wilbur Raff' },
    { id: 50, title: 'Nurse', name: 'Cordell Jaqueme' },
    { id: 51, title: 'Tax Accountant', name: 'Sam Clarycott' },
    { id: 52, title: 'Programmer I', name: 'Enid Burtt' },
    { id: 53, title: 'Biostatistician IV', name: 'Lon Klosterman' },
    { id: 54, title: 'Nurse', name: 'Moyra Gowrich' },
    { id: 55, title: 'Biostatistician I', name: 'Morganica Zavattieri' },
    { id: 56, title: 'Administrative Assistant I', name: 'Vladamir Heinsius' },
    { id: 57, title: 'Project Manager', name: 'Garald Girodon' },
    { id: 58, title: 'Quality Control Specialist', name: 'Tillie Fluger' },
    { id: 59, title: 'Operator', name: 'Willard Margeram' },
    { id: 60, title: 'Accounting Assistant III', name: 'Nels Sumers' },
    { id: 61, title: 'Professor', name: 'Estele Jantel' },
    { id: 62, title: 'Community Outreach Specialist', name: 'Barbette Dewhirst' },
    { id: 63, title: 'Registered Nurse', name: 'Lorilyn Tebbut' },
    { id: 64, title: 'Geologist IV', name: 'Adolpho Travis' },
    { id: 65, title: 'Structural Engineer', name: 'Roberta Curl' },
    { id: 66, title: 'Financial Advisor', name: 'Raddy Falshaw' },
    { id: 67, title: 'Accounting Assistant III', name: 'Jamesy Allawy' },
    { id: 68, title: 'Information Systems Manager', name: 'Selle Hazelhurst' },
    { id: 69, title: 'Safety Technician IV', name: 'Tatum Babonau' },
    { id: 70, title: 'Chemical Engineer', name: 'Dacie Malyan' },
    { id: 71, title: 'Chemical Engineer', name: 'Shela Gianiello' },
    { id: 72, title: 'Environmental Tech', name: 'Hortensia Dredge' },
    { id: 73, title: 'Programmer III', name: 'Yasmeen Mintrim' },
    { id: 74, title: 'Civil Engineer', name: 'Toni Brychan' },
    { id: 75, title: 'Paralegal', name: 'Gabi Lebond' },
    { id: 76, title: 'Senior Financial Analyst', name: 'Lesley Middler' },
    { id: 77, title: 'Design Engineer', name: 'Curt Vaughn' },
    { id: 78, title: 'Web Developer I', name: 'Sybille Dorsey' },
    { id: 79, title: 'Sales Associate', name: 'Marcelia LeEstut' },
    { id: 80, title: 'Librarian', name: 'Peg Stutard' },
    { id: 81, title: 'Environmental Tech', name: 'Brendon Dalla' },
    { id: 82, title: 'Executive Secretary', name: 'Barby Van der Brugge' },
    { id: 83, title: 'Marketing Assistant', name: 'Arabelle Knudsen' },
    { id: 84, title: 'Accounting Assistant I', name: 'Kimmi Wallage' },
    { id: 85, title: 'Web Developer IV', name: 'Malorie Gardener' },
    { id: 86, title: 'Statistician IV', name: 'Roanne Abbate' },
    { id: 87, title: 'Legal Assistant', name: 'Randie Ellingford' },
    { id: 88, title: 'Geological Engineer', name: 'Nester Drewell' },
    { id: 89, title: 'Financial Analyst', name: 'Anthe Dilks' },
    { id: 90, title: 'Environmental Specialist', name: 'Milly Rust' },
    { id: 91, title: 'Information Systems Manager', name: 'Gustie Rains' },
    { id: 92, title: 'Financial Advisor', name: 'Enrique Littledyke' },
    { id: 93, title: 'VP Product Management', name: 'Nathanil Portingale' },
    { id: 94, title: 'Senior Financial Analyst', name: 'Rafaellle Christer' },
    { id: 95, title: 'Nuclear Power Engineer', name: 'Kerianne Crosdill' },
    { id: 96, title: 'Financial Advisor', name: 'Henderson Ibbotson' },
    { id: 97, title: 'Librarian', name: 'Pyotr Gittens' },
    { id: 98, title: 'Administrative Officer', name: 'Ulrich McGowan' },
    { id: 99, title: 'Help Desk Technician', name: 'King Endecott' },
    { id: 100, title: 'Analog Circuit Design manager', name: 'Consalve Dyhouse' },
    { id: 101, title: 'Data Coordinator', name: 'Adara Rudwell' },
    { id: 102, title: 'Nuclear Power Engineer', name: 'Porty Fuller' },
    { id: 103, title: 'Internal Auditor', name: 'Baird Restill' },
    { id: 104, title: 'Research Nurse', name: 'Romy Marklow' },
    { id: 105, title: 'Computer Systems Analyst IV', name: 'Aldon Jarmain' },
    { id: 106, title: 'Project Manager', name: 'Torrence Sambeck' },
    { id: 107, title: 'Clinical Specialist', name: 'Emmott Kynett' },
    { id: 108, title: 'Senior Quality Engineer', name: 'Korrie Grewe' },
    { id: 109, title: 'Financial Analyst', name: 'Cleve Hannigane' },
    { id: 110, title: 'Occupational Therapist', name: 'Brunhilda Hynd' },
    { id: 111, title: 'Database Administrator IV', name: 'Adelle Greasty' },
    { id: 112, title: 'Professor', name: 'Nanon Aitkin' },
    { id: 113, title: 'Engineer III', name: 'Lorette Tondeur' },
    { id: 114, title: 'Physical Therapy Assistant', name: 'Cosette Lembrick' },
    { id: 115, title: 'VP Accounting', name: 'Tybie Figg' },
    { id: 116, title: 'Staff Scientist', name: 'Edlin Karpe' },
    { id: 117, title: 'Data Coordinator', name: 'Beckie Adamski' },
    { id: 118, title: 'Quality Control Specialist', name: 'Celestine Wormleighton' },
    { id: 119, title: 'Computer Systems Analyst III', name: 'Kingston Probbin' },
    { id: 120, title: 'Electrical Engineer', name: 'Clareta Govier' },
    { id: 121, title: 'Junior Executive', name: 'Tamqrah Kilius' },
    { id: 122, title: 'Professor', name: 'Danyelle Landre' },
    { id: 123, title: 'Automation Specialist I', name: 'Paloma Traske' },
    { id: 124, title: 'Environmental Specialist', name: 'Julienne Silley' },
    { id: 125, title: 'Mechanical Systems Engineer', name: 'Marjorie Aslett' },
    { id: 126, title: 'Automation Specialist II', name: 'Isidore Farrand' },
    { id: 127, title: 'Professor', name: 'Shirlee Anyene' },
    { id: 128, title: 'Recruiting Manager', name: 'Kacie Sawter' },
    { id: 129, title: 'Community Outreach Specialist', name: 'Sibbie Yurenin' },
    { id: 130, title: 'Structural Engineer', name: 'Malorie Pendlebury' },
    { id: 131, title: 'Product Engineer', name: 'Orella Richardin' },
    { id: 132, title: 'Account Executive', name: 'Ora Routley' },
    { id: 133, title: 'Occupational Therapist', name: 'Artemis Skey' },
    { id: 134, title: 'Account Executive', name: 'Conni Knoton' },
    { id: 135, title: 'Staff Accountant III', name: 'Dore Wartonby' },
    { id: 136, title: 'Human Resources Manager', name: 'Kerby Le Clercq' },
    { id: 137, title: 'Associate Professor', name: 'Roshelle Peare' },
    { id: 138, title: 'Human Resources Manager', name: 'Jehanna Cornick' },
    { id: 139, title: 'Senior Developer', name: 'Claude Burk' },
    { id: 140, title: 'Automation Specialist II', name: 'Tessie Ordelt' },
    { id: 141, title: 'Recruiter', name: 'Hewe Tennison' },
    { id: 142, title: 'Mechanical Systems Engineer', name: 'Nanci Leddie' },
    { id: 143, title: 'Systems Administrator I', name: 'Adan Ickovici' },
    { id: 144, title: 'Compensation Analyst', name: 'Cedric Stubbings' },
    { id: 145, title: 'Social Worker', name: 'Ashlin Timlett' },
    { id: 146, title: 'Recruiter', name: 'Cassy Rossey' },
    { id: 147, title: 'Engineer II', name: 'Cheri Tremathick' },
    { id: 148, title: 'Quality Engineer', name: 'Barnebas Bourbon' },
    { id: 149, title: 'Junior Executive', name: 'Wynny Greener' },
    { id: 150, title: 'Associate Professor', name: 'Jefferey Strowther' },
    { id: 151, title: 'Speech Pathologist', name: 'Dacy Salazar' },
    { id: 152, title: 'Quality Control Specialist', name: 'Doll Stanners' },
    { id: 153, title: 'Chief Design Engineer', name: 'Freddie Hachette' },
    { id: 154, title: 'VP Product Management', name: 'Amelina Simeons' },
    { id: 155, title: 'Senior Developer', name: 'Abbot Tohill' },
    { id: 156, title: 'Research Nurse', name: 'Siobhan Normadell' },
    { id: 157, title: 'General Manager', name: 'Tina Roxbrough' },
    { id: 158, title: 'Senior Financial Analyst', name: 'Lodovico Fussey' },
    { id: 159, title: 'Social Worker', name: 'Walther Jurges' },
    { id: 160, title: 'Environmental Specialist', name: 'Codie Litchmore' },
    { id: 161, title: 'Senior Quality Engineer', name: 'Meier Redsall' },
    { id: 162, title: 'Developer III', name: 'Paola Essex' },
    { id: 163, title: 'Occupational Therapist', name: 'Mellicent Schultz' },
    { id: 164, title: 'Geologist I', name: 'Malvina Tavinor' },
    { id: 165, title: 'Mechanical Systems Engineer', name: 'Rhetta Ewells' },
    { id: 166, title: 'Chief Design Engineer', name: 'Louisette Shead' },
    { id: 167, title: 'Office Assistant III', name: 'Land Kondratovich' },
    { id: 168, title: 'Programmer III', name: 'Anatole Fincke' },
    { id: 169, title: 'Web Designer I', name: 'Cecilia Yearnsley' },
    { id: 170, title: 'VP Quality Control', name: 'Samuel Sabbatier' },
    { id: 171, title: 'Project Manager', name: 'Tomkin Slorach' },
    { id: 172, title: 'Recruiter', name: 'Chastity Quaintance' },
    { id: 173, title: 'VP Sales', name: 'Emilie Finney' },
    { id: 174, title: 'Marketing Assistant', name: 'Ermanno Ivons' },
    { id: 175, title: 'Accounting Assistant IV', name: 'Arri Le Strange' },
    { id: 176, title: 'Recruiter', name: 'Zonnya Govier' },
    { id: 177, title: 'Quality Control Specialist', name: 'Darcy Cattlow' },
    { id: 178, title: 'Administrative Assistant I', name: 'Thorndike Daft' },
    { id: 179, title: 'Junior Executive', name: 'Stu Wadsworth' },
    { id: 180, title: 'Account Coordinator', name: 'Isidor Nisby' },
    { id: 181, title: 'Office Assistant II', name: 'Jacklyn Blewmen' },
    { id: 182, title: 'Cost Accountant', name: 'Cherie Farress' },
    { id: 183, title: 'Database Administrator II', name: 'Ariel Jiggens' },
    { id: 184, title: 'Civil Engineer', name: 'Bettye Currie' },
    { id: 185, title: 'Pharmacist', name: 'Creighton Cumberlidge' },
    { id: 186, title: 'Structural Analysis Engineer', name: 'Cal Dominguez' },
    { id: 187, title: 'Information Systems Manager', name: 'Valeria Farrell' },
    { id: 188, title: 'Senior Quality Engineer', name: 'Billi Baudrey' },
    { id: 189, title: 'VP Product Management', name: 'Jenny Taunton' },
    { id: 190, title: 'Media Manager IV', name: 'Christiane Spivey' },
    { id: 191, title: 'Data Coordinator', name: 'Helen-elizabeth MacCallion' },
    { id: 192, title: 'Staff Accountant II', name: 'Francyne Bridgestock' },
    { id: 193, title: 'Nuclear Power Engineer', name: 'Merwyn Matthai' },
    { id: 194, title: 'Financial Advisor', name: 'Sapphira Elderbrant' },
    { id: 195, title: 'Structural Analysis Engineer', name: 'Bonnibelle Dorgon' },
    { id: 196, title: 'Accountant III', name: "Madelon O'Tierney" },
    { id: 197, title: 'Budget/Accounting Analyst I', name: 'Robena Rivelon' },
    { id: 198, title: 'Senior Developer', name: 'Catlin Hussy' },
    { id: 199, title: 'Senior Editor', name: 'Ashton Scouse' },
    { id: 200, title: 'Research Associate', name: 'Dee dee Mulholland' },
    { id: 201, title: 'Research Associate', name: 'Edward Luesley' },
    { id: 202, title: 'Occupational Therapist', name: 'Yurik Geeve' },
    { id: 203, title: 'Environmental Specialist', name: 'Keenan Benardette' },
];
